# Generated by Django 5.2 on 2025-06-30 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='assignee',
            new_name='assigned_to',
        ),
    ]
