# Generated by Django 5.2 on 2025-06-30 20:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0005_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='url',
        ),
        migrations.AddField(
            model_name='file',
            name='file',
            field=models.FileField(default=django.utils.timezone.now, upload_to='files/'),
            preserve_default=False,
        ),
    ]
